# Generated by Django 4.1.7 on 2023-02-25 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_language_country_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='languages',
        ),
    ]
